### ISSUE TITLE
No CRC for VLD data

### ISSUE THREAD

**Issue by ARao0123** [plan44/p44vdc#2]
Hi,

In enoceancomm.cpp, you've added this comment "Radio telegram data (in ESP3, does not contain data checksum crc, e.g. for VLD)". Can you please point me to the documentation which confirms this. 
I am a bit confused on ERP1 and ERP2 and ESP3. Is CRC not available for any telegram that is ERP1 version but available for ERP2?

**Comment by plan44** [comment]
Hi Amritha,

> In enoceancomm.cpp, you've added this comment "Radio telegram data (in ESP3, does not contain data checksum crc, e.g. for VLD)". Can you please point me to the documentation which confirms this.

It's in the ESP3 (Enocean Serial Protocol) specification, available here: https://www.enocean.com/fileadmin/redaktion/pdf/tec_docs/EnOceanSerialProtocol3.pdf
Specificially, in paragraph "2.1.1 Packet structure" it states: "The actual user data (variable length) is a *subset* of the radio telegram.", which means that the ESP3 packet does not contain *all* bytes that are in the actual radio packets.

> I am a bit confused on ERP1 and ERP2 and ESP3.

Back when I wrote that code, I was confused, too ;-) That's why I put that comment into the code...

> Is CRC not available for any telegram that is ERP1 version but available for ERP2?

ESP3 (the serial byte protocol used to communicate with an EnOcean modem module, such as the TCM310) is an *abstraction* of the actual radio telegrams. It mostly hides the details and differences of ERP1 and ERP2. And as the modem checks the radio checksums/CRCs, there is no need for them to be represented in the ESP3 packet. An application using ESP3 (like p44vdc) does not need to know or care about the radio CRCs, the modem takes care of these. On the ESP3 level you have the header and data CRCs to ensure ESP3 packet integrity, but this is completely separate from the radio CRCs.

Hope this helps!

Best Regards
Lukas

**Comment by ARao0123** [comment]
That helps a lot thanks!
Just wanted to confirm few things if you don't mind.
-  The CRC is not present only for VLD but all 1BS and 4BS packets have them?
- VLD packets are only supported in ERP1? ERP2 supports only 1BS and 4BS? I ask this because section 2.9.1 (packet structure for ERP2) does not talk about VLD.

**Comment by plan44** [comment]
To be honest, I don't really know, because I always used EnOcean via the ESP3 which abstracts those details away.
So I haven't dug into the details of how the higher level packets (RPS, 1BS, 4BS, VLD) are mapped to ERP1 and ERP2.

As far as I understand, ERP2 is only for the US and Japan markets in the 902 and 928 MHz bands. So far, I've been working with 868Mhz European EnOcean devices only, so I guess I've never had to deal with ESP2 at all.

However I just found in paragraph 2.5.30 of the ESP3 specs: by default, modems run in the "compatible" mode, which apparently (AFAIK) means that even ERP2 packets are delivered via the ERP1 ESP3 packet type 1.

So it seems the explicit ERP2 packet type 10 is needed for special cases only, whereas you normally work with ERP2 via the packet type 1. That might be the reason why VLD is not mentioned specifically together with ERP2. But just guessing here…

**Comment by ARao0123** [comment]
Thanks a ton :)
